### PR TITLE
fix: upgrade go to the latest go1.18 minor version

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

- Upgrades tekton to 0.32.4
- Upgrades k8s client libraries to 0.22.X
- Pins opentelemtry packages to 0.19.X for now to fix build

### CODE REVIEW

**Review by tomhobson — APPROVED** [review]

**Review by rajatgupta24 — APPROVED** [review]
👍🏻

**Comment by ankitm123** [comment]
related to https://github.com/jenkins-x/jx/issues/8283

**Comment by ankitm123** [comment]
Changes to test files are related to @rajatgupta24 's change to add message to pipeline activity: https://github.com/jenkins-x-plugins/jx-pipeline/pull/481

**Pull request merged**
